# Generated by APEBind. Do not edit directly.
from __future__ import annotations

import json
from pathlib import Path

from ._runtime import APEClient


_OPERATIONS = json.loads(r'''{}''')
_RUNTIME = json.loads(r'''{
  "env_unset": []
}''')
_CLIENT = APEClient(
    Path(__file__).with_name('bin') / 'ffmpeg.com',
    _OPERATIONS,
    _RUNTIME,
)


def raw(arguments: list[str], persistent: bool = False):
    return _CLIENT.raw(arguments, persistent=persistent)
