// Generated by APEBind. Do not edit directly.
import type {
  APEProcessResult,
  ProcessSession,
  RawOptions,
} from './_runtime.js';

export interface ClientOptions {
  environment?: Readonly<Record<string, string | undefined>>;
}

export function createClient(options?: ClientOptions): import('./_runtime.js').APEClient;

export function raw(
  arguments_: readonly unknown[],
  options?: RawOptions,
): Promise<APEProcessResult | ProcessSession>;
