// Generated by APEBind. Do not edit directly.
import { fileURLToPath } from 'node:url';

import { APEClient } from './_runtime.js';

const OPERATIONS = {};
const RUNTIME = {
  "env_unset": []
};

export function createClient({ environment = {} } = {}) {
  return new APEClient(
    fileURLToPath(new URL('./bin/ffmpeg.com', import.meta.url)),
    OPERATIONS,
    RUNTIME,
    environment,
  );
}

const CLIENT = createClient();

export async function raw(arguments_, options = {}) {
  return CLIENT.raw(arguments_, options);
}
